# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - develop
    working_directory: ~/tasklist
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.0-node
         enviroment:
           PGHOST: 127.0.0.1
           PGUSER: postgres
           RAILS_ENV: test
      
       - image: circleci/postgres:9.5-alpine
         enviroment:
           POGTGRES_USER: postgres
           POGTGRES_DB: tasklist_test
           POGTGRES_PASSWORD: ""
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

#    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:schema:load --trace &&
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://postgres@localhost:5432/tasklist_test"